core/accounts/urls.py
from django.urls import path, include
from .views import CustomLoginView, RegisterPage
from django.contrib.auth.views import LogoutView

app_name = "accounts"

urlpatterns = [
    # path("login", views.login_view, name="login"),
    # path("logout", views.logout_view, name="logout"),
    # path("register", views.register_view, name="register"),
    path("login/", CustomLoginView.as_view(), name="login"),
    path("logout", LogoutView.as_view(next_page="/"), name="logout"),
    path("register/", RegisterPage.as_view(), name="register"),
    path("api/v1/", include("accounts.api.v1.urls")),
]

core/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.http import HttpResponseRedirect
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

...

schema_view = get_schema_view(
    openapi.Info(
        title="todo API",
        default_version="v1",
        description="This is a test api for maktabkhooneh project",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="amirali@gmail.com"),
        license=openapi.License(name="MIT License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)


def redirectToApp(request):
    return HttpResponseRedirect("/todo")


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", redirectToApp, name="index"),
    path("accounts/", include("accounts.urls")),
    path("todo/", include("todo.urls")),
    path("weather/", include("weather.urls")),
    path("api-auth/", include("rest_framework.urls")),
    path(
        "swagger/output.json",
        schema_view.without_ui(cache_timeout=0),
        name="schema-json",
    ),
    path(
        "swagger/",
        schema_view.with_ui("swagger", cache_timeout=0),
        name="schema-swagger-ui",
    ),
    path(
        "redoc/",
        schema_view.with_ui("redoc", cache_timeout=0),
        name="schema-redoc",
    ),
    path("captcha/", include("captcha.urls")),
]

# serving static and media for development
if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT
    )
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

core/todo/urls.py
from django.urls import path, include
from .views import (
    TaskList,
    TaskCreate,
    TaskComplete,
    TaskUpdate,
    DeleteView,
)

app_name = "todo"

urlpatterns = [
    # path("", views.index, name="task_list"),
    # path("update/<str:pk>/", views.updateTask, name="update_task"),
    # path("complete/<str:pk>/", views.completeTask, name="complete_task"),
    # path("delete/<str:pk>/", views.deleteTask, name="delete_task"),
    path("", TaskList.as_view(), name="task_list"),
    path("create/", TaskCreate.as_view(), name="create_task"),
    path("update/<int:pk>/", TaskUpdate.as_view(), name="update_task"),
    path("complete/<int:pk>/", TaskComplete.as_view(), name="complete_task"),
    path("delete/<int:pk>/", DeleteView.as_view(), name="delete_task"),
    path("api/v1/", include("todo.api.v1.urls")),
]

core/weather/urls.py
from django.urls import path
from .views import WeatherView

urlpatterns = [
    path("<str:city>/", WeatherView.as_view(), name="weather"),
]

core/todo/models.py
from django.db import models
from django.contrib.auth import get_user_model

# Create your models here.
User = get_user_model()


class Task(models.Model):
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, null=True, blank=True
    )
    title = models.CharField(max_length=200)
    complete = models.BooleanField(default=False)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    class Meta:
        order_with_respect_to = "user"

core/weather/models.py
# from django.db import models

# Create your models here.

core/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import get_user_model
from captcha.fields import CaptchaField

User = get_user_model()


class CustomUserCreationForm(UserCreationForm):
    captcha = CaptchaField()

    class Meta:
        model = User
        fields = ("email",)


class CustomAuthenticationForm(AuthenticationForm):
    username = forms.EmailField(
        widget=forms.TextInput(attrs={"autofocus": True})
    )

core/todo/forms.py
from django import forms
from .models import Task


class TaskForm(forms.ModelForm):
    title = forms.CharField(
        widget=forms.TextInput(attrs={"placeholder": "Add new task..."})
    )

    class Meta:
        model = Task
        fields = ("title",)

core/accounts/api/v1/views.py
from rest_framework import generics
from .seializers import (
    RegistrationSerializer,
    CustomAuthTokenSerializer,
    CustomTokenObtainPairViewSerializer,
    ActivationResendSerializer,
    ChangePasswordSerializer,
    PasswordResetRequestViewSerializer,
    PasswordResetConfirmSerializer,
)
from django.contrib.auth import get_user_model
from rest_framework.response import Response
from rest_framework import status
from rest_framework.authtoken.views import ObtainAuthToken, Token
from rest_framework.views import APIView
from rest_framework.permissions import IsAuthenticated
from rest_framework_simplejwt.views import TokenObtainPairView
import jwt
from django.conf import settings
from jwt.exceptions import ExpiredSignatureError, InvalidSignatureError
from rest_framework_simplejwt.tokens import RefreshToken
from mail_templated import EmailMessage
from ..utils import EmailThread
from django.shortcuts import get_object_or_404
from django.utils.http import urlsafe_base64_encode
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_decode
from django.contrib.auth.tokens import default_token_generator

User = get_user_model()


class RegistrationApiView(generics.GenericAPIView):
    serializer_class = RegistrationSerializer

    def post(self, request, *args, **kwargs):
        serializer = RegistrationSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            email = serializer.validated_data["email"]
            user_obj = get_object_or_404(User, email=email)
            token = self.get_tokens_for_user(user_obj)
            email_obj = EmailMessage(
                "email/activation_email.tpl", {"token": token}, to=[email]
            )
            EmailThread(email_obj).start()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    def get_tokens_for_user(self, user):
        refresh = RefreshToken.for_user(user)
        return str(refresh.access_token)


class CustomObtainAuthToken(ObtainAuthToken):
    serializer_class = CustomAuthTokenSerializer

    def post(self, request, *args, **kwargs):
        serializer = self.get_serializer(
            data=request.data, context={"request": request}
        )
        serializer.is_valid(raise_exception=True)
        user = serializer.validated_data["user"]
        token, created = Token.objects.get_or_create(user=user)
        return Response(
            {
                "token": token.key,
                "user_id": user.pk,
                "email": user.email,
            }
        )


class CustomDiscardAuthToken(APIView):
    permission_classes = [IsAuthenticated]

    def post(self, request):
        request.user.auth_token.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)


class CustomTokenObtainPairView(TokenObtainPairView):
    serializer_class = CustomTokenObtainPairViewSerializer


class ActivationApiView(APIView):
    def get(self, request, token, *args, **kwargs):
        try:
            token = jwt.decode(
                token, settings.SECRET_KEY, algorithms=["HS256"]
            )
            user_id = token.get("user_id")
        except ExpiredSignatureError:
            return Response(
                {"detail": "token has been expired"},
                status=status.HTTP_400_BAD_REQUEST,
            )
        except InvalidSignatureError:
            return Response(
                {"detail": "token is not valid"},
                status=status.HTTP_400_BAD_REQUEST,
            )
        user_obj = User.objects.get(pk=user_id)
        if user_obj.is_verified:
            return Response(
                {"detail": "your account has already been verified"}
            )
        user_obj.is_verified = True
        user_obj.save()
        return Response(
            {
                "detail": "your account have been verified "
                "and activated successfully"
            }
        )


class ActivationResendApiView(generics.GenericAPIView):
    serializer_class = ActivationResendSerializer

    def post(self, request, *args, **kwargs):
        serializer = ActivationResendSerializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        user_obj = serializer._validated_data["user"]
        token = self.get_tokens_for_user(user_obj)
        email_obj = EmailMessage(
            "email/activation_email.tpl",
            {"token": token},
            to=[user_obj.email],
        )
        EmailThread(email_obj).start()
        return Response(
            {"detail": "user activation resend succesfully"},
            status=status.HTTP_200_OK,
        )

    def get_tokens_for_user(self, user):
        refresh = RefreshToken.for_user(user)
        return str(refresh.access_token)


class ChangePasswordApiView(generics.GenericAPIView):
    model = User
    permission_classes = [IsAuthenticated]
    serializer_class = ChangePasswordSerializer

    def get_object(self, queryset=None):
        obj = self.request.user
        return obj

    def put(self, request, *args, **kwargs):
        self.object = self.get_object()
        serializer = self.get_serializer(data=request.data)
        if serializer.is_valid():
            # Check old password
            if not self.object.check_password(
                serializer.data.get("old_password")
            ):
                return Response(
                    {"old_password": ["Wrong password."]},
                    status=status.HTTP_400_BAD_REQUEST,
                )
            # set_password also hashes the password that the user will get
            self.object.set_password(serializer.data.get("new_password"))
            self.object.save()
            return Response(
                {"detail": "password change successfully"},
                status=status.HTTP_200_OK,
            )
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class PasswordResetRequestView(generics.GenericAPIView):
    serializer_class = PasswordResetRequestViewSerializer

    def post(self, request):
        serializer = PasswordResetRequestViewSerializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        user_obj = serializer._validated_data["user"]

        uid = urlsafe_base64_encode(force_bytes(user_obj.pk))
        token = default_token_generator.make_token(user_obj)
        email_obj = EmailMessage(
            "email/reset_password.tpl",
            {"token": token, "uid": uid},
            to=[user_obj],
        )
        EmailThread(email_obj).start()
        return Response(
            {"detail": "Reset link sent"},
            status=status.HTTP_200_OK,
        )


class PasswordResetConfirmView(generics.GenericAPIView):
    serializer_class = PasswordResetConfirmSerializer

    def post(self, request, uidb64, token):
        serializer = PasswordResetConfirmSerializer(data=request.data)
        serializer.is_valid(raise_exception=True)

        try:
            uid = urlsafe_base64_decode(uidb64).decode()
            user = User.objects.get(pk=uid)
        except (User.DoesNotExist, ValueError, TypeError):
            return Response(
                {"detail": "Invalid link"}, status=status.HTTP_400_BAD_REQUEST
            )

        if not default_token_generator.check_token(user, token):
            return Response(
                {"detail": "Invalid or expired token"},
                status=status.HTTP_400_BAD_REQUEST,
            )

        user.set_password(serializer.validated_data["new_password"])
        user.save()

        return Response(
            {"detail": "Password reset successful"}, status=status.HTTP_200_OK
        )

core/accounts/views.py
from django.shortcuts import redirect
from django.contrib.auth import login

# from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
# from django.contrib.auth.decorators import login_required

from django.contrib.auth.views import LoginView
from django.views.generic.edit import FormView
from django.urls import reverse_lazy
from .forms import CustomUserCreationForm, CustomAuthenticationForm

# Create your views here.

# FBV
"""
def login_view(request):
    if not request.user.is_authenticated:
        if request.method == "POST":
            form = AuthenticationForm(request=request, data=request.POST)
            if form.is_valid():
                username = form.cleaned_data.get("username")
                password = form.cleaned_data.get("password")
                user = authenticate(request,
                                    username=username, password=password)
                if user is not None:
                    login(request, user)
                    return redirect("/")
            else:
                return render(request, 'accounts/login.html', {"form":form})
        form = AuthenticationForm()
        context = {"form": form}
        return render(request, "accounts/login.html", context)
    else:
        return redirect("/")
"""


# CBV
class CustomLoginView(LoginView):
    template_name = "accounts/login.html"
    authentication_form = CustomAuthenticationForm
    redirect_authenticated_user = True

    def form_valid(self, form):
        print("فرم اعتبارسنجی شد و کاربر:", form.get_user())
        return super().form_valid(form)

    def form_invalid(self, form):
        print("فرم نامعتبر:", form.errors)
        return super().form_invalid(form)

    def get_success_url(self):
        return reverse_lazy("todo:task_list")


"""
@login_required
def logout_view(request):
    logout(request)
    return redirect("/")

def register_view(request):
    if not request.user.is_authenticated:
        if request.method == "POST":
            form = UserCreationForm(request.POST)
            if form.is_valid():
                form.save()
                username = form.cleaned_data.get("username")
                password = form.cleaned_data.get("password")
                user = authenticate(request,
                username=username, password=password)
                if user is not None:
                    login(request, user)
                    redirect("/")
            else:
                return render(request,
                'accounts/register.html', {"form":form})
        form = UserCreationForm()
        context = {"form": form}
        return render(request, "accounts/register.html", context)
    else:
        return redirect("/")
"""


class RegisterPage(FormView):
    template_name = "accounts/register.html"
    form_class = CustomUserCreationForm
    redirect_authenticated_user = True
    success_url = reverse_lazy("todo:task_list")

    def form_valid(self, form):
        user = form.save()
        if user is not None:
            login(self.request, user)
        return super(RegisterPage, self).form_valid(form)

    def get(self, *args, **kwargs):
        if self.request.user.is_authenticated:
            return redirect("todo:task_list")
        return super(RegisterPage, self).get(*args, **kwargs)

core/weather/views.py
from django.utils.decorators import method_decorator
from django.views.decorators.cache import cache_page
from rest_framework.views import APIView
from rest_framework.response import Response
import requests

# Create your views here.


@method_decorator(cache_page(60 * 20), name="dispatch")
class WeatherView(APIView):
    def get(self, request, city, *args, **kwargs):
        response = requests.get(
            f"https://api.openweathermap.org/data/2.5/weather?"
            f"q={city}&appid=YOUR_API_KEY"
        )
        return Response(response.json())

core/templates/accounts/login.html
{% extends "base.html" %}

{% block title %} Login {% endblock %}

{% block extra_css %}

<link href="https://getbootstrap.com/docs/5.1/examples/sign-in/signin.css" rel="stylesheet">
{% endblock %}


{% block content %}
<main class="form-signin text-center">
    <form action="{% url 'accounts:login' %}" method="POST">
        <h1 class="h3 mb-3 fw-normal">Please Sign In</h1>
        {% csrf_token %}
        <div class="form-floating">
            <input type="email" name="username" class="form-control" id="floatingInput"
                placeholder="name@example.com">
            <label for="floatingInput">Email</label>
        </div>
        <div class="form-floating">
            <input type="password" name="password" class="form-control" id="floatingPassword" placeholder="Password">
            <label for="floatingPassword">Password</label>
        </div>

        <div class="checkbox mb-3">
            <label>
                <input type="checkbox" value="remember-me"> Remember me
            </label>
        </div>
        <button class="w-100 btn btn-lg btn-primary" type="submit">Sign in</button>
        <p class="mt-3 mb-2">Dont have an account then <a href="{% url 'accounts:register' %}">create one</a></p>
        <p class="mt-5 mb-3 text-muted">&copy; 2017–2021</p>
    </form>
    {% if form.errors %}
    <div class="alert alert-error">
        <h6>Please fix the following errors</h6>
        <ul>
            {% for field in form %}
            {% if field.errors %}
            {% for error in field.errors %}
            <li><a href="#id_{{ field.name }}" class="error">{{ error|escape }}</a></li>
            {% endfor %}
            {% endif %}
            {% endfor %}
        </ul>
        {% if form.non_field_errors %}
        {{ form.non_field_errors }}
        {% endif %}
    </div>
    {% endif %}
</main>
{% endblock content %}

core/templates/accounts/register.html
{% extends "base.html" %}

{% block title %} Register {% endblock %}

{% block extra_css %}
<link href="https://getbootstrap.com/docs/5.1/examples/sign-in/signin.css" rel="stylesheet">
{% endblock %}

{% block content %}
<main class="form-signin text-center">
    <form action="{% url 'accounts:register' %}" method="POST">
        <h1 class="h3 mb-3 fw-normal">Please Register</h1>
        {% csrf_token %}
        <div class="form-floating">
            <input type="email" name="email" class="form-control" id="floatingInput"
                placeholder="name@example.com">
            <label for="floatingInput">Email</label>
        </div>
        <div class="form-floating">
            <input type="password" name="password1" class="form-control mb-0" id="floatingPassword"
                placeholder="Password">
            <label for="floatingPassword">Password</label>
        </div>
        <div class="form-floating">
            <input type="password" name="password2" class="form-control" id="floatingPassword" placeholder="Password">
            <label for="floatingPassword">Repeate Password</label>
        </div>
        <div class="mb-3">
            <label for="id_captcha" class="form-label">کد امنیتی</label>
            <div class="d-flex align-items-center gap-3">
            {{ form.captcha.image }}  
            {{ form.captcha }}        
        </div>
        {% if form.captcha.errors %}
        <div class="text-danger small">
            {{ form.captcha.errors.0 }}
        </div>
    {% endif %}
</div>


        <button class="w-100 btn btn-lg btn-primary" type="submit">Register</button>
        <p class="mt-3 mb-2">Already have an account then <a href="{% url 'accounts:login' %}"> login</a></p>
        <p class="mt-5 mb-3 text-muted">&copy; 2017–2021</p>
    </form>
    {% if form.errors %}
    <div class="alert alert-error">
        <h6>Please fix the following errors</h6>
        <ul>
            {% for field in form %}
            {% if field.errors %}
            {% for error in field.errors %}
            <li><a href="#id_{{ field.name }}" class="error">{{ error|escape }}</a></li>
            {% endfor %}
            {% endif %}
            {% endfor %}
        </ul>
        {% if form.non_field_errors %}
        {{ form.non_field_errors }}
        {% endif %}
    </div>
    {% endif %}
</main>


{% endblock %}